### ISSUE TITLE
Why not use GitHub's `funding.yml` thing?

### ISSUE THREAD

**Issue by fiatjaf** [Kixunil/ln-donate#1]
Or whatever it's called, I'm not sure how they do it.

**Comment by Kixunil** [comment]
Oh, didn't know, will check what it is.

**Comment by Kixunil** [comment]
So GH allows you to enter up to four HTTPS URLs. I specifically tried `lightning:...` URL and it failed to parse. (Would it make sense to have some kind of LNURL discovery spec?) So this plugin could still offer a bit of convenience. Also some tools processing repositories automatically could be used even if one doesn't use GitHub.

I will document this and then close the issue. If you have any other ideas feel free to reply!

**Comment by fiatjaf** [comment]
Yeah, of course GitHub won't support it for now, but we can still write it there and then this plugin could parse the `lightning:` URLs there.

**Comment by Kixunil** [comment]
We can not write anything out-of-spec there, otherwise we will get error. So the fallback https idea is the only way.
